name: sqlite-ctrlx
version: 2.0.01
summary: Simple SQLite database
description: |
  Writing a node will exectue the SQL statement on the SQLite database. Reading returns the result of the last succesful operation. 
base: core20
confinement: strict
grade: stable


apps:
  provider:
    command: bin/main.py
    plugs: 
      - network
      - datalayer
    daemon: simple
    passthrough:   
      restart-condition: always
      restart-delay: 10s

parts:
  provider:
    plugin: python
    source: .

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

  datalayerdeb:
    plugin: dump
    source: ./tmp/ctrlx-datalayer.deb
    source-type: deb
    stage-packages:
      - libzmq5
    override-pull: |
      mkdir -p ../../../tmp/
      cp ../../../deb/ctrlx-datalayer-1.*.*.deb ../../../tmp/ctrlx-datalayer.deb
      snapcraftctl pull
    override-prime: |
      rm -rf ../tmp
      snapcraftctl prime 

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions

